Meta: add infrastructure to generate summary.json
WebKit/standards-positions pull request #208
Opened 2023-06-20 15:44 UTC by annevk

The setup is as follows:

1. We collect all the issue data from the repository through the GitHub API and store it in a JSON file. Storing the input allows us to monitor changes in it for bugs. We'll likely want to change some issues so they are more suitable for consumption by the script.
2. The script takes this data and produces a JSON file with a summarized view of each issue. The bulk of the logic is in processing the body of the issue (the top comment) which is split between before and after the YAML change.

The idea is that the JSON file with the summarized view can be consumed and eventually displayed on webkit.org once we're happy with it.

It currently has some flaws due to the raw data, but it seems worthwhile to check this in and then improve the raw data to validate the entire process around updating the issue data.

2023-06-20 15:56 UTC, hober approved these changes
looks good to me; one nit

2023-06-20 15:56 UTC, hober commented on summary.py
> +            temp_data = json.loads(requests.get(f"https://api.github.com/repos/WebKit/standards-positions/issues?direction=asc&state=all&per_page=100&page={page}").text)
should probably pass in a timeout duration & handle it

2023-06-21 11:51 UTC, annevk commented on summary.py
> +            return True
Heh, thanks! I had made a similar change locally (though using a tuple) when I needed to add "`invalid`".

2023-06-21 17:56 UTC, gsnedders reviewed
Here's a lot of comments.

You might want to run `black` on this to reformat this to meet expected code style, and you may also want to run `flake8` on this and see what errors it finds?

2023-06-21 17:56 UTC, gsnedders commented on summary.py
> +        data = json.load(open("summary-data.json", "r"))
```suggestion
        with open("summary-data.json", "rb") as f:
            data = json.load(f)
```

Similarly, close the file. Also avoid decoding the file using whatever encoding Python is configured to use, and let the JSON decoder just figure it out.

2023-06-23 05:54 UTC, karlcow requested changes
Currently the code resides in the root directory. 
It would probably be better in a separate directory. 
![Screenshot 2023-06-23 at 14 49 39](https://github.com/WebKit/standards-positions/assets/505230/2aa6f6fe-6f7c-4f72-a155-48c4c0a144c4)


Specifically when adding a couple of things for managing the tests, etc. 

Could we move all of that in a tooling or something.

Also should  the edits on `summary.py` be separated from `summary.json` and `summary-data.json`

I would propose we do. 

```
.github/
data/
   summary-data.json
   summary.json
tooling/
    summary.py
    tests/
```

I will be working on testing later. Once the first PR is merged.

2023-06-23 05:59 UTC, karlcow commented
> Also should the edits on `summary.py` be separated from `summary.json` and `summary-data.json`

It could even be part of a GitHub actions. So that we have a clear separation in between editing the python factory and the data generations.

2023-06-23 14:09 UTC, gsnedders commented
> It could even be part of a GitHub actions.

One could reasonably imagine the `summary.json` getting pushed to `gh-pages`, so it could be used by others.

2023-06-26 12:41 UTC, annevk commented on summary.py
> +            break
I don't think it's that simple. I could replace the continue/break with an else/break branch (and then perhaps flip the branches), but I kinda liked this personally.

2023-06-26 12:49 UTC, annevk commented on summary.py
> +#!/usr/bin/env python
Is it really best practice to put the version number there? It works fine either way.

2023-06-26 12:53 UTC, karlcow commented on summary.py
> +#!/usr/bin/env python
Let's assume this is python 3, and we can set a requirements after.

2023-06-27 02:44 UTC, karlcow commented
> I like the idea of more automation, but changing `summary.json` through PRs is important for review purposes in my opinion. We want to be somewhat careful about what ends up on the website. I could see running the update process in a more automated fashion, but for now that seems more wasteful than useful to me.

At least would it be possible to do different PRs for python code and data file generation. 🙏

2023-06-27 11:09 UTC, annevk commented
I doubt we're going to change the code a whole lot after this lands and a reviewer probably wants to see the changes doing the right thing?

2023-06-28 09:33 UTC, merged